drop table if exists t1;
create table t1(i int, j int, k int);
insert into t1 values(1, 10, 100);
insert into t1 values(1, 11, 110);
insert into t1 values(2, 20, 200);
insert into t1 values(2, 22, 220);
insert into t1 values(3, 30, 300);
insert into t1 values(3, 33, 330);
select i, sum(j), min(k) from t1 group by i;
drop table if exists t2;
create table t2 as select * from t1;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
select count(*) from t2;
drop table if exists t3;
create table t3(i int, j int, k int);
insert into t3(i) select generate_series(1,50000);--50000 groups
update t3 set j=100, k=1000;
insert into t3 select * from t3;
insert into t3 select * from t3;
insert into t3 select * from t3;
insert into t3 select * from t3;
insert into t3 select * from t3;
insert into t3 select * from t3;
insert into t3 select * from t3;
insert into t3 select * from t3;
select count(*) from t3;
create table t4 as select * from t3;
insert into t4 select * from t4;
select count(*) from t4;
